# Generated by Django 5.2.2 on 2025-06-11 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='pages',
            new_name='copy_total',
        ),
        migrations.AlterField(
            model_name='acessdocstatistic',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics_doc', to='biblioteca.document'),
        ),
        migrations.AlterField(
            model_name='acessdocstatistic',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DocumentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='group_document_permissions', to='biblioteca.document')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='document_group_permissios', to='auth.group')),
            ],
        ),
    ]
